version: "3.5"
services:
  pop-solr:
    image: solr:9.3.0
    command:
      - "-c"
      - "-a"
      - "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:58983"
      - "-Dsolr.ext.libs.dir=/opt/solr/ext-libs"
      - "-Denable.packages=true"
    restart: always
    healthcheck:
      test: lsof -n -i :8983
      interval: 30s
      timeout: 3s
      retries: 3
