version: "3.5"
services:
  gatling-solr:
    environment:
      SOLR_REQUESTLOG_ENABLED: "true"
    deploy:
      resources:
        limits:
          memory: 2048M
    network_mode: host
    volumes:
      - gatling-solr-vol:/var/solr
volumes:
  gatling-solr-vol:
    name: gatling-solr-vol
